[package]
name = "videah-net"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-html = "0.1.0"
dioxus = { version = "0.2.4", features = ["web", "fermi"] }
dyn-clonable = "0.9.0"
dyn-clone = "1.0.5"
enum-as-inner = "0.5.0"
im-rc = "15.1.0"
markdown = "0.3.0"
markdown-to-html = "0.1.2"
phf = { version = "0.10.1", features = ["macros"] }
snailquote = "0.3.1"
stdweb = "0.4.20"
strum = { version = "0.24.0", features = ["derive"] }
wasm-bindgen = "0.2.80"
web-sys = { version = "0.3.57", features = ["Location", "Window", "Element", "Document", "HtmlElement"] }

[build-dependencies]
built = "0.5"
